apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # The amount of storage requested by the PersistentVolumeClaim (1Gi = 1 gibibyte).  